### ISSUE TITLE
不错啊，不过支付宝支付升级了，代码得添加对新支付接口的升级才行啊

### ISSUE THREAD

**Issue by csharpweb** [hiihellox10/ICanPay#1]
不错啊，不过支付宝支付升级了，代码得添加对新支付接口的升级才行啊，
我就是来找大家的共享库进来的，不过是支付宝的新的支付开放平台的。

**Comment by hiihellox10** [comment]
现在的实现是网站支付常用的即时到帐支付功能。支付宝的开放平台的API主要是给手机用的，提供的是扫描支付宝用户的付款二维码来扣款的功能，另外还有和微信一样用户扫描商家的付款二维码来付款的功能，因为这功能需要实体店铺才能申请所以未增加。
